# Generated by Django 5.0.6 on 2024-06-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_course_paid_alter_payment_subject_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="id платежа"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Статус платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
